name: portfolio_web
description: "A personal portfolio website built with Flutter."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^12.1.1
  url_launcher: ^6.1.10
  google_fonts: ^6.3.1
  flutter_animate: ^4.2.0
  responsive_framework: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.7.2

flutter:
  uses-material-design: true
  # assets:
  # - assets/images/
  # - assets/data/
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont-Regular.ttf
        - asset: assets/fonts/CustomFont-Bold.ttf
          weight: 700
        - asset: assets/fonts/CustomFont-Italic.ttf
